namespace CarMarket.Web.Models.CamperModel
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;

    public static class Brand
    {
        public static readonly Dictionary<string, string> BrandList = new Dictionary<string, string>
        {
            { "1", "ABI" },
            { "2", "Adria" },
            { "3", "Ahorn" },
            { "4", "Alcar" },
            { "5", "Alpha" },
            { "6", "Alpine" },
            { "7", "Arca" },
            { "8", "Autoroller" },
            { "9", "Autostar" },
            { "10", "Avento" },
            { "11", "Avondale" },
            { "12", "Award" },
            { "13", "Bavaria-Camp" },
            { "14", "Bawemo" },
            { "15", "Benimar" },
            { "16", "Bergland" },
            { "17", "Beyerland" },
            { "18", "Bimobil" },
            { "19", "Burow" },
            { "20", "Bursner" },
            { "21", "Burstner" },
            { "22", "CA-MO-CAR" },
            { "23", "Carado" },
            { "24", "Caravelair" },
            { "25", "Caro" },
            { "26", "Carthago" },
            { "27", "Challenger" },
            { "28", "Chateau" },
            { "29", "Chausson" },
            { "30", "Ci International" },
            { "31", "Citroen" },
            { "32", "Coachmen" },
            { "33", "Concorde" },
            { "34", "Cristall" },
            { "35", "CS Reisemobile" },
            { "36", "Daystar" },
            { "37", "Dehler" },
            { "38", "Delta" },
            { "39", "Dethleffs" },
            { "40", "Due Erre" },
            { "41", "Eifelland" },
            { "42", "Elnagh" },
            { "43", "Eriba" },
            { "44", "Esterel" },
            { "45", "Euramobil" },
            { "46", "Euro Liner" },
            { "47", "EVM" },
            { "48", "Fendt" },
            { "49", "FFB - Tabbert" },
            { "50", "Fiat" },
            { "51", "Fleetwood" },
            { "52", "Ford" },
            { "53", "FR-Mobil" },
            { "54", "Frankia" },
            { "55", "Granduca" },
            { "56", "Hehn" },
            { "57", "Heku" },
            { "58", "Hobby" },
            { "59", "Holiday Rambler" },
            { "60", "Hymer" },
            { "61", "Iveco" },
            { "62", "JOINT" },
            { "63", "Karmann" },
            { "64", "Keystone" },
            { "65", "Kip" },
            { "66", "Knaus" },
            { "67", "La Strada" },
            { "68", "Laika" },
            { "69", "LMC" },
            { "70", "Lunar" },
            { "71", "M+M Mobile" },
            { "72", "Mc Louis" },
            { "73", "Mercedes-Benz" },
            { "74", "Mirage" },
            { "75", "Mobilvetta" },
            { "76", "Monaco" },
            { "77", "Moncayo" },
            { "78", "Movera" },
            { "79", "Munsterland" },
            { "80", "Niesmann Bischoff" },
            { "81", "Nordstar" },
            { "82", "Ormocar" },
            { "83", "Peugeot" },
            { "84", "Phoenix" },
            { "85", "Pilote" },
            { "86", "Possl" },
            { "87", "Rapido" },
            { "88", "Reimo" },
            { "89", "Reisemobile Beier" },
            { "90", "Rimor" },
            { "91", "Riva" },
            { "92", "Riviera" },
            { "93", "RMB" },
            { "94", "Roadtrek" },
            { "95", "Robel-Mobil" },
            { "96", "Rockwood" },
            { "97", "Scania" },
            { "98", "Sea" },
            { "99", "Selbstbau" },
            { "100", "Shato" },
            { "101", "SLOOP" },
            { "102", "Sprite" },
            { "103", "Sterckeman" },
            { "104", "SUNLIGHT" },
            { "105", "Sunroller" },
            { "106", "Tabbert" },
            { "107", "TEC" },
            { "108", "Tischer" },
            { "109", "Triple E" },
            { "110", "Vario" },
            { "111", "Vitesse" },
            { "112", "VW" },
            { "113", "Weinsberg" },
            { "114", "Weippert" },
            { "115", "Westfalia" },
            { "116", "Wilk" },
            { "117", "Winnebago" },
            { "118", "Woelcke" }
        };
    }
}