namespace CarMarket.Web.Models.CarModel
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;

    public static class Brand
    {
        public static readonly Dictionary<string, string> BrandList = new Dictionary<string, string>
        {
            { "1", "Acura" },
            { "2", "Aixam" },
            { "3", "Alfa Romeo" },
            { "4", "Alpina" },
            { "5", "Aro" },
            { "6", "Asia Motors" },
            { "7", "Aston Martin" },
            { "8", "Audi" },
            { "9", "Austin" },
            { "10", "Bentley" },
            { "11", "Bmw" },
            { "12", "Borgward" },
            { "13", "Brilliance" },
            { "14", "Bugatti" },
            { "15", "Buick" },
            { "16", "Cadillac" },
            { "17", "Chevrolet" },
            { "18", "Chrysler" },
            { "19", "Citroen" },
            { "20", "Corvette" },
            { "21", "Dacia" },
            { "22", "Daewoo" },
            { "23", "DAF" },
            { "24", "Daihatsu" },
            { "25", "Datsun" },
            { "26", "Dodge" },
            { "27", "DR" },
            { "28", "Excalibur" },
            { "29", "Ferrari" },
            { "30", "Fiat" },
            { "31", "Ford" },
            { "32", "Foton" },
            { "33", "Gac Gonow" },
            { "34", "GAZ" },
            { "35", "Geo" },
            { "36", "Gillet" },
            { "37", "GMC" },
            { "38", "Great Wall" },
            { "39", "HIGER" },
            { "40", "Honda" },
            { "41", "Humber" },
            { "42", "Hummer" },
            { "43", "Hyundai" },
            { "44", "Ikarus" },
            { "45", "Infinity" },
            { "46", "Isuzu" },
            { "47", "Iveco" },
            { "48", "Jaguar" },
            { "49", "Jeep" },
            { "50", "Kia" },
            { "51", "Koenigsegg" },
            { "52", "Ktm" },
            { "53", "Lada" },
            { "54", "Lamborghini" },
            { "55", "Lancia" },
            { "56", "Land Rover" },
            { "57", "Landwind" },
            { "58", "Latvia" },
            { "59", "LDV" },
            { "60", "Lexus" },
            { "61", "Ligier" },
            { "62", "Lincoln" },
            { "63", "Lotus" },
            { "64", "Mahindra" },
            { "65", "MAN" },
            { "66", "Martin Motors" },
            { "67", "Maserati" },
            { "68", "Matra" },
            { "69", "Maybach" },
            { "70", "Mazda" },
            { "71", "McLaren" },
            { "72", "Mercedes-Benz" },
            { "73", "MG" },
            { "74", "Microcar" },
            { "75", "Mini" },
            { "76", "Mitsubishi" },
            { "77", "Morgan" },
            { "78", "Moskvich" },
            { "79", "Neoplan" },
            { "80", "Nissan" },
            { "81", "NSU" },
            { "82", "Oldsmobile" },
            { "83", "Oltsit" },
            { "84", "Opel" },
            { "85", "Peugeot" },
            { "86", "Piaggio" },
            { "87", "Plymouth" },
            { "88", "Pontiac" },
            { "89", "Porsche" },
            { "90", "Range Rover" },
            { "91", "Renault" },
            { "92", "Rolls Royce" },
            { "93", "Rover" },
            { "94", "Saab" },
            { "95", "Samand" },
            { "96", "Santana" },
            { "97", "Scania" },
            { "98", "Scion" },
            { "99", "Seat" },
            { "100", "Setra" },
            { "101", "Shuanghuan" },
            { "102", "Skoda" },
            { "103", "Smart" },
            { "104", "Ssangyong" },
            { "105", "STOEWER" },
            { "106", "Subaru" },
            { "107", "Suzuki" }, 
            { "108", "Talbot" },
            { "109", "Tata" },
            { "110", "Tempo" },
            { "111", "Temsa" },
            { "112", "Tesla" },
            { "113", "Toyota" },
            { "114", "Trabant" },
            { "115", "Triumph" },
            { "116", "TVR" },
            { "117", "UAZ" },
            { "118", "Volga" },
            { "119", "Volvo" },
            { "120", "Vromos" },
            { "121", "VW" },
            { "122", "Wartburg" },
            { "123", "Wiesmann" }, 
            { "124", "Zastava" },
            { "125", "Zaz" },
            { "126", "ВАЗ" },
            { "127", "Варшава" },
            { "128", "София" },
        };
    }
}