namespace CarMarket.Web.Models.TruckModel
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;

    public static class Brand
    {
        public static readonly Dictionary<string, string> BrandList = new Dictionary<string, string>
        {
            { "1", "ACERBI" },
            { "2", "ADIGE" },
            { "3", "Astra" },
            { "4", "Avia" },
            { "5", "Barkas" },
            { "6", "Berna" },
            { "7", "Bmc" },
            { "8", "Carnehl" },
            { "9", "Citroen" },
            { "10", "Daf" },
            { "11", "Daimler" },
            { "12", "Dennis" },
            { "13", "DFSK" },
            { "14", "Dodge" },
            { "15", "Eduards" },
            { "16", "Erf" },
            { "17", "Fabela" },
            { "18", "Faun" },
            { "19", "Fedra" },
            { "20", "Fiat" },
            { "21", "Fliegl" },
            { "22", "Foden" },
            { "23", "Ford" },
            { "24", "Gaz" },
            { "25", "Ginaf" },
            { "26", "Hanomag" },
            { "27", "Henshel" },
            { "28", "Hino" },
            { "29", "Hyundai" },
            { "30", "lelch" },
            { "31", "Ifa" },
            { "32", "Ikarus" },
            { "33", "Inter" },
            { "34", "International" },
            { "35", "Isuzu" },
            { "36", "Iveco" },
            { "37", "Jum" },
            { "38", "Jumbo" },
            { "39", "Kamaz" },
            { "40", "Kia" },
            { "41", "King Long" },
            { "42", "Kraz" },
            { "43", "Langendorf" },
            { "44", "LECITRALER" },
            { "45", "Leiland" },
            { "46", "Liaz" },
            { "47", "Lt" },
            { "48", "Luaz" },
            { "49", "M&G" },
            { "50", "Mack" },
            { "51", "Magerus" },
            { "52", "Man" },
            { "53", "Man-vw" },
            { "54", "Maz" },
            { "55", "Mazda" },
            { "56", "Mega" },
            { "57", "Mercedes" },
            { "58", "Mini" },
            { "59", "MIROFRET" },
            { "60", "Mitsubishi" },
            { "61", "Montenegro" },
            { "62", "Nisa" },
            { "63", "Nissan" },
            { "64", "Om" },
            { "65", "OMSP" },
            { "66", "Opel" },
            { "67", "PANAV" },
            { "68", "Peugeot" },
            { "69", "Piaggio" },
            { "70", "Praga" },
            { "71", "Preslav" },
            { "72", "Raba" },
            { "73", "Renault" },
            { "74", "Robur" },
            { "75", "Rolfo" },
            { "76", "Roman" },
            { "77", "Rover" },
            { "78", "Scania" },
            { "79", "Schmitz" },
            { "80", "Schwartzmuller" },
            { "81", "Seat" },
            { "82", "Seres" },
            { "83", "Setra" },
            { "84", "Skoda" },
            { "85", "Steyr" },
            { "86", "STRASSER" },
            { "87", "Tatra" },
            { "88", "Terberg" },
            { "89", "Toyota" },
            { "90", "Trail" },
            { "91", "Uaz" },
            { "92", "Ural" },
            { "93", "Volvo" },
            { "94", "Vw" },
            { "95", "Zastava" },
            { "96", "Zil" },
            { "97", "Ремарке" },
            { "98", "Цистерна" },
            { "99", "Чавдар" },
        };
    }
}